<script lang="ts">
  import type { Snippet } from "svelte";

  export type DataVisualizationKind = "bars" | "distribution" | "donut" | "line";

  let {
    children,
    clientWidth = $bindable(0),
    kind,
  }: {
    children: Snippet;
    clientWidth?: number;
    kind: DataVisualizationKind;
  } = $props();
</script>

<div
  class={[
    "min-w-0",
    kind === "line" &&
      "mt-visualization-section-wide overflow-x-auto pb-visualization-scroll visualization-svg:block visualization-svg:w-full visualization-svg:h-auto visualization-svg:overflow-visible visualization-grid-line:stroke-line visualization-grid-line:stroke-1 visualization-grid-text:fill-ink-faint visualization-grid-text:font-body visualization-grid-text:text-stat-chart-meta visualization-grid-text:font-stat-chart-meta visualization-grid-text:tabular-nums visualization-grid-text:text-anchor-end visualization-line:fill-none visualization-line:stroke-chart-1 visualization-line:stroke-3 visualization-line:stroke-visualization-round visualization-line-previous:stroke-chart-2 visualization-line-previous:stroke-visualization-comparison visualization-line-previous:stroke-dasharray-visualization-comparison visualization-point:fill-surface visualization-point:stroke-chart-1 visualization-point:stroke-3 visualization-point-previous:stroke-chart-2 visualization-point-previous:stroke-visualization-comparison visualization-label:fill-ink-faint visualization-label:font-body visualization-label:text-stat-chart-meta visualization-label:font-stat-chart-meta visualization-label:tabular-nums visualization-label:capitalize visualization-label:text-anchor-middle",
    kind === "distribution" &&
      "mt-visualization-section grid gap-md visualization-summary:w-fit visualization-summary:-mt-xs visualization-summary:rounded-visualization-summary visualization-summary:bg-surface-subtle visualization-summary:px-visualization-summary-inline visualization-summary:py-visualization-summary-block visualization-summary:text-ink-soft visualization-summary:text-stat-chart-label visualization-summary:font-stat-chart-label visualization-list:grid visualization-list:gap-visualization-list visualization-row:grid visualization-row:gap-visualization-row visualization-row-label:flex visualization-row-label:min-w-0 visualization-row-label:items-baseline visualization-row-label:justify-between visualization-row-label:gap-md visualization-row-label-title:overflow-hidden visualization-row-label-title:text-ink visualization-row-label-title:text-stat-chart-label visualization-row-label-title:font-stat-chart-label visualization-row-label-title:text-ellipsis visualization-row-label-title:whitespace-nowrap visualization-row-label-meta:flex-none visualization-row-label-meta:text-ink-faint visualization-row-label-meta:text-stat-chart-meta visualization-row-label-meta:font-stat-chart-meta visualization-row-label-meta:tabular-nums visualization-row-label-value:text-ink-soft visualization-row-label-value:text-stat-chart-value visualization-row-label-value:font-stat-chart-value visualization-bars:relative visualization-bars:grid visualization-bars:h-visualization-bar visualization-bars:items-center visualization-bars:overflow-hidden visualization-bars:rounded-control visualization-bars:bg-surface-subtle visualization-bar:absolute visualization-bar:left-0 visualization-bar:h-visualization-bar visualization-bar:rounded-control visualization-bar:bg-chart-1 visualization-bar-previous:z-1 visualization-bar-previous:h-visualization-comparison-bar visualization-bar-previous:bg-chart-2",
    kind === "donut" &&
      "mt-visualization-section grid grid-cols-visualization-donut items-center gap-lg visualization-donut-chart:relative visualization-donut-chart:w-visualization-donut visualization-donut-chart:aspect-square visualization-donut-chart:justify-self-center visualization-donut-svg:block visualization-donut-svg:size-full visualization-donut-svg:-rotate-90 visualization-donut-track:fill-none visualization-donut-track:stroke-surface-subtle visualization-donut-track:stroke-15 visualization-donut-segment:fill-none visualization-donut-segment:stroke-chart-1 visualization-donut-segment:stroke-15 visualization-donut-segment-previous:stroke-chart-2 visualization-donut-center:absolute visualization-donut-center:inset-0 visualization-donut-center:grid visualization-donut-center:place-content-center visualization-donut-center:text-ink visualization-donut-center:text-center visualization-donut-value:text-stat-chart-value visualization-donut-value:font-stat-chart-value visualization-donut-value:leading-visualization-donut visualization-donut-value:tabular-nums visualization-donut-meta:mt-xs visualization-donut-meta:text-ink-faint visualization-donut-meta:text-stat-chart-meta visualization-donut-meta:font-stat-chart-meta visualization-donut-legend:grid visualization-donut-legend:min-w-0 visualization-donut-legend:gap-md visualization-donut-legend:m-0 visualization-donut-legend-item:relative visualization-donut-legend-item:grid visualization-donut-legend-item:gap-visualization-legend-copy visualization-donut-legend-item:pl-lg visualization-donut-swatch:absolute visualization-donut-swatch:top-visualization-swatch-top visualization-donut-swatch:left-0 visualization-donut-swatch:size-visualization-swatch visualization-donut-swatch:rounded-visualization-swatch visualization-donut-swatch:bg-chart-1 visualization-donut-swatch-previous:bg-chart-2 visualization-donut-term:text-ink-soft visualization-donut-term:text-stat-chart-label visualization-donut-term:font-stat-chart-label visualization-donut-description:flex visualization-donut-description:items-baseline visualization-donut-description:gap-visualization-description visualization-donut-description:m-0 visualization-donut-description:text-ink visualization-donut-description:tabular-nums visualization-donut-description-value:text-stat-chart-value visualization-donut-description-value:font-stat-chart-value visualization-donut-description-meta:text-ink-faint visualization-donut-description-meta:text-stat-chart-meta visualization-donut-description-meta:font-stat-chart-meta",
    kind === "bars" &&
      "mt-visualization-section overflow-x-auto pb-visualization-scroll visualization-hour-plot:grid visualization-hour-plot:h-visualization-hour-plot visualization-hour-plot:gap-xs visualization-hour-plot:pt-sm visualization-hour-plot:border-b visualization-hour-plot:border-line-strong visualization-hour-plot:bg-visualization-grid md:visualization-hour-plot:h-visualization-hour-plot-wide visualization-hour:grid visualization-hour:min-w-0 visualization-hour:grid-rows-visualization-hour visualization-hour:gap-visualization-hour visualization-hour:text-center visualization-hour-bars:flex visualization-hour-bars:min-w-0 visualization-hour-bars:items-end visualization-hour-bars:justify-center visualization-hour-bars:gap-visualization-hour-bars visualization-hour-bar:w-visualization-hour-bar visualization-hour-bar:min-h-px visualization-hour-bar:rounded-t-visualization-bar visualization-hour-bar:bg-chart-1 visualization-hour-bar:transition-visualization-bar visualization-hour-bar-previous:bg-chart-2 visualization-hour-bar-previous:opacity-visualization-comparison visualization-hour-value:overflow-hidden visualization-hour-value:text-ink-soft visualization-hour-value:text-stat-chart-value visualization-hour-value:font-stat-chart-value visualization-hour-value:leading-visualization-hour-value visualization-hour-value:tabular-nums visualization-hour-value:text-ellipsis visualization-hour-value:whitespace-nowrap visualization-hour-label:self-center visualization-hour-label:text-ink-faint visualization-hour-label:text-stat-chart-meta visualization-hour-label:font-stat-chart-meta visualization-hour-label:tabular-nums",
  ]}
  data-ui="data-visualization"
  data-kind={kind}
  bind:clientWidth
>
  {@render children()}
</div>
